---
language: python
python: "2.7"

env:
  - ANSIBLE_VERSION=2.6.5
  - ANSIBLE_VERSION=2.7.10
  - ANSIBLE_VERSION=latest

before_install:
  - sudo apt-get update -qq

install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  # Syntax check
  - "ansible-playbook -i localhost, test/test_server.yml --syntax-check"
  - "ansible-playbook -i localhost, test/test_sentinel.yml --syntax-check"
  # Test Redis Server
  - "ansible-playbook -i localhost, test/test_server.yml --connection=local --become"
  # Idempotency check
  - >
    ansible-playbook -i localhost, test/test_server.yml --connection=local --become
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotency: PASS' && exit 0)
    || (echo 'Idempotency: FAIL' && exit 1)
  # Test Redis Sentinel
  - "ansible-playbook -i localhost, test/test_sentinel.yml --connection=local --become"
  # Connection test
  - "/opt/redis/bin/redis-cli PING"
  - "/opt/redis/bin/redis-cli -p 26379 PING"
  # Facts syntax check
  - >
    sudo cat /etc/ansible/facts.d/redis.fact
    | python -m json.tool
    && (echo 'Facts syntax: PASS' && exit 0)
    || (echo 'Facts syntax: FAIL' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
