---
- name: install debian dependencies
  apt:
    pkg: "{{ redis_apt_dependencies }}"
    update_cache: yes
    cache_valid_time: 86400
    state: present
  retries: "{{ remote_package_retries }}"
  register: apt_result
  until: apt_result is succeeded
  when: ansible_os_family == "Debian"

- name: install redhat dependencies
  yum:
    name: "{{ redis_yum_dependencies }}"
    state: present
  retries: "{{ remote_package_retries }}"
  register: yum_result
  until: yum_result is succeeded
  when: ansible_os_family == "RedHat"

# Conditionally install the i686 build of libgcc if we are building 32-bit
# It must be version-locked with x64 libgcc, so use 'latest' to update libgcc first
# Otherwise you get a version mismatch error from yum when installing.
- name: update libgcc on rhel for 32-bit dependencies
  yum:
    name: libgcc
    state: latest
  retries: "{{ remote_package_retries }}"
  register: yum_result
  until: yum_result is succeeded
  when: ansible_os_family == "RedHat" and redis_make_32bit|bool

- name: install redhat 32-bit dependencies
  yum:
    name: "{{ redis_yum_32bit_dependencies }}"
    state: latest
  retries: "{{ remote_package_retries }}"
  register: yum_result
  until: yum_result is succeeded
  when: ansible_os_family == "RedHat" and redis_make_32bit|bool

- name: install suse dependencies
  zypper:
    name: "{{ redis_zypper_dependencies }}"
    state: present
  retries: "{{ remote_package_retries }}"
  register: zyp_result
  until: zyp_result is succeeded
  when: ansible_os_family == 'Suse'
